name: Build/release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      is_tag: ${{ startsWith(github.ref, 'refs/tags/') }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-22.04-arm64]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - run: pnpm run build -r electron -t 33.0.0
      - run: pnpm run build -r node -t 20.0.0 -t 22.0.0

      - name: release
        if: env.is_tag == 'true'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: false
          artifacts: "prebuilds/*.tar.gz"
          replacesArtifacts: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload win artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ runner.os }}
          path: |
            prebuilds

permissions:
  contents: write
